# Generated by Django 5.1 on 2024-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.IntegerField(unique=True)),
                ('tipo_cama', models.CharField(max_length=50)),
                ('accesorios', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignada', 'Asignada'), ('Mantenimiento', 'Mantenimiento')], max_length=15)),
            ],
        ),
    ]
