# Generated by Django 5.1 on 2024-11-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
