# Generated by Django 5.1 on 2024-11-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
